# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/blockchain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/blockchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/blockchain.proto\x12\x11\x63oe892.blockchain\"6\n\x0fGetChainRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nfrom_index\x18\x02 \x01(\x05\"P\n\rChainResponse\x12/\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x1f.coe892.blockchain.BlockMessage\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\x7f\n\x0c\x42lockMessage\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x15\n\rprevious_hash\x18\x03 \x01(\t\x12\r\n\x05nonce\x18\x04 \x01(\x05\x12\x0c\n\x04hash\x18\x05 \x01(\t\x12\x19\n\x11transactions_json\x18\x06 \x01(\t\";\n\x13StreamBlocksRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x66ter_index\x18\x02 \x01(\x05\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x85\x02\n\x0e\x42lockchainNode\x12P\n\x08GetChain\x12\".coe892.blockchain.GetChainRequest\x1a .coe892.blockchain.ChainResponse\x12\x46\n\x0bSubmitBlock\x12\x1f.coe892.blockchain.BlockMessage\x1a\x16.coe892.blockchain.Ack\x12Y\n\x0cStreamBlocks\x12&.coe892.blockchain.StreamBlocksRequest\x1a\x1f.coe892.blockchain.BlockMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.blockchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCHAINREQUEST']._serialized_start=45
  _globals['_GETCHAINREQUEST']._serialized_end=99
  _globals['_CHAINRESPONSE']._serialized_start=101
  _globals['_CHAINRESPONSE']._serialized_end=181
  _globals['_BLOCKMESSAGE']._serialized_start=183
  _globals['_BLOCKMESSAGE']._serialized_end=310
  _globals['_STREAMBLOCKSREQUEST']._serialized_start=312
  _globals['_STREAMBLOCKSREQUEST']._serialized_end=371
  _globals['_ACK']._serialized_start=373
  _globals['_ACK']._serialized_end=407
  _globals['_BLOCKCHAINNODE']._serialized_start=410
  _globals['_BLOCKCHAINNODE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
